### ISSUE TITLE
Tween strings?

### ISSUE THREAD

**Issue by twobit** [chenglou/react-tween-state#21] opened 2015-02-13 01:00 UTC
In some cases strings need to be tweened e.g. rgb or path strings. It seems I would have to override the `_getTweeningValue` function.

**Comment by chenglou** [comment] 2015-02-13 09:16
Anything that can be tween has, by definition, a numerical representation. You should never have to override that function. In the case of e.g. color, you'd have a tweened decimal number. Then, in your render, you'd use a generic `decimalToHex` function + `hexToWhateverCSSFormat` function operating on the decimal value you got.

This is by design. The job of this library is to tween, not to convert from the tweened result to a format x. One day we should pull out https://github.com/less/less.js/blob/6fd2a5751cc8313481913bcb1623bf6c50089df8/lib/less/tree/color.js and https://github.com/less/less.js/blob/6fd2a5751cc8313481913bcb1623bf6c50089df8/lib/less/functions/color.js so that people can reuse these on normal js collections/values.

Does that make sense? If so, I'll close this =)

**Comment by chenglou** [comment] 2015-02-13 09:23
Also, if you _really_ feel like working with strings and sugar coat the complexity that comes with it, you can always have something like this:

```js
function myLinearTweenForColorStr(currentTime, beginValue, endValue, totalDuration) {
  var a = colorStringToDecimal(beginValue);
  var b = colorStringToDecimal(endValue);
  var y = tweenState.easingTypes.linear(currentTIme, a, b, totalDuration);
  return decimalToColorString(y);
}
```

**Comment by davidmfreese** [comment] 2015-02-13 13:32
Close away :-)

On Friday, February 13, 2015, Cheng Lou <notifications@github.com> wrote:

> Anything that can be tween has, by definition, a numerical representation.
> You should never have to override that function. In the case of e.g. color,
> you'd have a tweened decimal number. Then, in your render, you'd use a
> generic decimalToHex function + hexToWhateverCSSFormat function operating
> on the decimal value you got.
>
> This is by design. The job of this library is to tween, not to convert
> from the tweened result to a format x. One day we should pull out
> https://github.com/less/less.js/blob/6fd2a5751cc8313481913bcb1623bf6c50089df8/lib/less/tree/color.js
> and
> https://github.com/less/less.js/blob/6fd2a5751cc8313481913bcb1623bf6c50089df8/lib/less/functions/color.js
> so that people can reuse these on normal js collections/values.
>
> Does that make sense? If so, I'll close this =)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chenglou/react-tween-state/issues/21#issuecomment-74225270>
> .
>


-- 
David Freese, E.I.T.

**Closed** 2015-02-13 15:54 UTC

**Comment by chenglou** [comment] 2015-02-13 15:55
@twobit hope that answered your question though?

**Comment by twobit** [comment] 2015-02-13 18:48
Thanks @chenglou. RGB wasn't a great example, something like path data can be an unknown amount of scalars. #22 better expresses my problem.
